"""Render docs/06_test_evidence.md from recorded run files — never from hand-typed numbers.

Inputs: evidence/test_results.json (written by tests/conftest.py when MOBLAB_EVIDENCE_OUT is set)
and evidence/e2e_story.json (written by the Chromium story test when MOBLAB_E2E_STORY_OUT is set).
"""
from __future__ import annotations

import re
import tomllib
from collections import defaultdict
from pathlib import Path

from .paths import ACCEPTANCE_DIR, DOCS_DIR
from .queries import load_evidence

REQ_ROW = re.compile(r"^\| (REQ-[A-Z]+-\d{2}) \| (M|S) \| (.+?) \| ")


def requirement_titles() -> dict[str, tuple[str, str]]:
    out = {}
    for line in (DOCS_DIR / "02_requirements.md").read_text(encoding="utf-8").splitlines():
        m = REQ_ROW.match(line)
        if m:
            out[m.group(1)] = (m.group(2), m.group(3))
    return out


def _md(text: str) -> str:
    return str(text).replace("|", "\\|").replace("\n", " ")


def render() -> str:
    ev = load_evidence()
    story = load_evidence("e2e_story.json")
    scenarios = tomllib.loads((ACCEPTANCE_DIR / "acceptance_scenarios.toml").read_text(encoding="utf-8"))["scenario"]
    reqs = requirement_titles()
    lines = ["# 06 · Test evidence (generated)", "",
             "> Generated by `python -m moblab evidence` from `evidence/test_results.json` and `evidence/e2e_story.json`.",
             "> Do not edit by hand. These are **developer acceptance checks** run by the AI implementer. They are not",
             "> external UAT, and no business signoff exists.", ""]
    if not ev:
        lines.append("No recorded run found. Run the commands under *Reproduce* first.")
        return "\n".join(lines) + "\n"

    counts = ev["counts"]
    total = sum(counts.values())
    lines += ["## Recorded run", "",
              "| Field | Value |", "|---|---|",
              f"| Generated (UTC) | {ev['generated_at_utc']} |",
              f"| Code commit tested | `{ev['git_head']}`{' (working tree had uncommitted changes)' if ev['git_worktree_dirty'] else ' (clean working tree)'} |",
              f"| Python / platform | {ev['python']} / {_md(ev['platform'])} |",
              f"| Selection | {ev.get('selection') or 'full suite: service, HTTP, launcher and Chromium browser tests'} |",
              f"| pytest exit status | {ev['pytest_exit_status']} |",
              f"| Results | **{counts.get('passed', 0)} passed**, {counts.get('failed', 0)} failed, {counts.get('skipped', 0)} skipped, {counts.get('error', 0)} errors ({total} recorded results) |",
              "", "Counting rule: each parametrised case counts once. For example, the 24 policy examples are 24 results. "
              "No result is counted twice, and nothing was added by hand.", ""]

    failed = [r for r in ev["results"] if r["outcome"] not in ("passed",)]
    lines += ["## Failures and skips", ""]
    if failed:
        lines += ["| Test | Outcome | Reason |", "|---|---|---|"]
        lines += [f"| `{_md(r['nodeid'])}` | {r['outcome']} | {_md(r.get('skip_reason', ''))} |" for r in failed]
    else:
        lines.append("None in this run.")
    lines.append("")

    by_req = defaultdict(list)
    by_ac = defaultdict(list)
    for r in ev["results"]:
        for req in r["req"]:
            by_req[req].append(r)
        for ac in r["ac"]:
            by_ac[ac].append(r)

    lines += ["## Requirement → automated evidence", "",
              "| Requirement | Pri | Statement (short) | Results | Passed | Failed/Skipped | Example tests |", "|---|---|---|---|---|---|---|"]
    uncovered = []
    for req, (pri, title) in reqs.items():
        rs = by_req.get(req, [])
        if not rs:
            uncovered.append(req)
        passed = sum(1 for r in rs if r["outcome"] == "passed")
        other = len(rs) - passed
        names = sorted({r["nodeid"].split("::")[-1].split("[")[0] for r in rs})
        shown = ", ".join(f"`{n}`" for n in names[:3]) + (f" +{len(names) - 3} more" if len(names) > 3 else "")
        plain = title.replace("**", "").replace("`", "")
        short = plain if len(plain) <= 110 else plain[:107].rstrip() + "…"
        lines.append(f"| {req} | {pri} | {_md(short)} | {len(rs)} | {passed} | {other} | {shown or '—'} |")
    lines += ["", f"Requirements with no automated result: {', '.join(uncovered) if uncovered else 'none'}.", ""]

    lines += ["## Scenario → automated evidence", "",
              "| Scenario | Title | Results | Passed | Failed/Skipped | External UAT |", "|---|---|---|---|---|---|"]
    for s in scenarios:
        rs = by_ac.get(s["id"], [])
        passed = sum(1 for r in rs if r["outcome"] == "passed")
        lines.append(f"| {s['id']} | {_md(s['title'])} | {len(rs)} | {passed} | {len(rs) - passed} | not performed |")
    lines.append("")

    if story:
        lines += ["## Recorded Chromium story", "",
                  f"{story['browser']}; viewports {', '.join(story['viewports'])}; {story['server']}.",
                  f"Recorded {story['generated_at_utc']} on commit `{story['git_head']}`"
                  f"{' (working tree had uncommitted changes)' if story['git_worktree_dirty'] else ''}.",
                  f"Console errors: {len(story['console_errors'])}, all expected: they are the browser's resource errors "
                  f"for the intentional 4xx refusals ({len(story['console_errors_expected'])} expected)."
                  if sorted(story['console_errors']) == sorted(story['console_errors_expected'])
                  else f"Console errors: {story['console_errors']}", "",
                  "| # | Actor | Action | Expected | Observed in the browser/DB | Screenshot |", "|---|---|---|---|---|---|"]
        for i, st in enumerate(story["steps"], 1):
            shot = f"[{st['screenshot']}](screenshots/{st['screenshot']})" if st.get("screenshot") else "—"
            lines.append(f"| {i} | {_md(st['actor'])} | {_md(st['action'])} | {_md(st['expected'])} | {_md(st['observed'])} | {shot} |")
        lines += ["", "Layout measurements taken at each screenshot (page overflow in px, squashed headers, "
                  "tables needing sideways scrolling):", "",
                  "| Screenshot | Desktop overflow | Narrow overflow | Squashed headers | Desktop scrolling tables | Narrow scrolling tables (allowed) |",
                  "|---|---|---|---|---|---|"]
        for sh in story["screenshots"]:
            d, n = sh["desktop"], sh["narrow"]
            lines.append(f"| {sh['name']} | {d['overflow_px']} | {n['overflow_px']} | "
                         f"{len(d['squashed_headers']) + len(n['squashed_headers'])} | {len(d['scrolling_tables'])} | "
                         f"{', '.join(n['scrolling_tables']) or '—'} |")
        lines.append("")

    lines += ["## Reproduce", "",
              "The recording runs **twice**. `tests/test_docs.py` checks links to the generated files "
              "(screenshots, this page, the replay), and those exist only after a first pass. On a fresh "
              "checkout without them, the first pass reports those link checks as failed and the replay check as skipped (TH-05).", "",
              "```bash",
              "python3 -m venv .venv && .venv/bin/python -m pip install -r requirements-dev.txt",
              "# Chromium for Playwright (skip if your machine already provides it):",
              ".venv/bin/python -m playwright install chromium",
              "export MOBLAB_EVIDENCE_OUT=evidence/test_results.json MOBLAB_E2E_STORY_OUT=evidence/e2e_story.json \\",
              "       MOBLAB_SCREENSHOT_DIR=docs/screenshots MOBLAB_SCREENSHOT_FORMAT=jpg",
              "for pass in 1 2; do",
              "  .venv/bin/python -m pytest -q tests",
              "  .venv/bin/python -m moblab evidence && .venv/bin/python -m moblab build-replay",
              "done", "```", ""]
    return "\n".join(lines)


START, END = "<!-- evidence:start (generated by python -m moblab evidence) -->", "<!-- evidence:end -->"


def snapshot_block() -> str:
    """Short, generated evidence summary embedded in the release recommendation."""
    ev = load_evidence()
    story = load_evidence("e2e_story.json")
    if not ev:
        return "_No recorded run yet._"
    reqs = requirement_titles()
    by_req = defaultdict(list)
    by_ac = defaultdict(list)
    for r in ev["results"]:
        for x in r["req"]:
            by_req[x].append(r["outcome"])
        for x in r["ac"]:
            by_ac[x].append(r["outcome"])
    must = [k for k, (pri, _) in reqs.items() if pri == "M"]
    passing = [k for k in reqs if by_req.get(k) and all(o == "passed" for o in by_req[k])]
    must_passing = [k for k in must if k in passing]
    scenarios = tomllib.loads((ACCEPTANCE_DIR / "acceptance_scenarios.toml").read_text(encoding="utf-8"))["scenario"]
    ac_passing = [s["id"] for s in scenarios if by_ac.get(s["id"]) and all(o == "passed" for o in by_ac[s["id"]])]
    defects = (DOCS_DIR / "defect_log.md").read_text(encoding="utf-8")
    fixed = len(re.findall(r"^\| DEF-\d{3} .*\| Fixed \|$", defects, re.M))
    open_defects = len(re.findall(r"^\| DEF-\d{3} ", defects, re.M)) - fixed
    c = ev["counts"]
    rows = [
        "| Evidence item | Recorded value |", "|---|---|",
        f"| Recorded run | {ev['generated_at_utc']}, code commit `{ev['git_head'][:12]}`"
        f"{' (uncommitted changes present)' if ev['git_worktree_dirty'] else ' (clean tree)'} |",
        f"| Automated results | {c.get('passed', 0)} passed, {c.get('failed', 0)} failed, {c.get('skipped', 0)} skipped |",
        f"| Requirements with only passing results | {len(passing)} of {len(reqs)} (must-have: {len(must_passing)} of {len(must)}) |",
        f"| Scenarios with only passing checks | {len(ac_passing)} of {len(scenarios)} |",
        f"| Recorded browser story | {len(story['steps']) if story else 0} observed steps, {len(story['screenshots']) if story else 0} screens at 1440 px and 390 px |",
        f"| Product defects in the log | {fixed} fixed with regression tests, {open_defects} open |",
        "| External UAT / business signoff | **Not performed** |",
    ]
    return "\n".join(rows)


def _update_block(path: Path, block: str) -> None:
    text = path.read_text(encoding="utf-8")
    if START in text and END in text:
        head, rest = text.split(START, 1)
        _, tail = rest.split(END, 1)
        path.write_text(f"{head}{START}\n{block}\n{END}{tail}", encoding="utf-8")


def write_evidence_doc() -> Path:
    path = DOCS_DIR / "06_test_evidence.md"
    path.write_text(render(), encoding="utf-8")
    rec = DOCS_DIR / "07_release_recommendation.md"
    if rec.exists():
        _update_block(rec, snapshot_block())
    return path
